"""Hand-curated gift products that DummyJSON does not cover.

Each row: (slug, name, category, price, ship_days, stock, pexels_query,
           description, interests, occasions, recipients)

Images are fetched from Pexels by `pexels_query` in scripts/seed_catalog.py.
Vocabularies used for occasions/recipients live in app/services/taxonomy.py.
"""

G = tuple  # readability alias

CURATED = [
    # --- Coffee & tea --------------------------------------------------------
    G(("pour-over-coffee-set", "Ceramic Pour-Over Coffee Set", "coffee-tea", 42.0, 3, 25, "pour over coffee dripper",
       "Hand-glazed ceramic dripper, carafe and two cups for slow morning coffee.",
       ["coffee", "cooking", "slow living"], ["birthday", "housewarming", "just_because", "fathers_day"], ["dad", "friend", "partner", "coworker", "anyone"])),
    G(("single-origin-coffee-trio", "Single-Origin Coffee Trio", "coffee-tea", 34.0, 2, 40, "coffee beans bags",
       "Three 250g bags of freshly roasted beans from Ethiopia, Colombia and Sumatra.",
       ["coffee"], ["birthday", "thank_you", "christmas", "just_because"], ["dad", "boss", "coworker", "friend", "anyone"])),
    G(("matcha-starter-kit", "Matcha Starter Kit", "coffee-tea", 48.0, 3, 18, "matcha whisk bowl",
       "Ceremonial-grade matcha with bamboo whisk, scoop and chawan bowl.",
       ["tea", "wellness", "japanese culture"], ["birthday", "just_because", "get_well"], ["her", "friend", "partner", "sibling"])),
    G(("loose-leaf-tea-sampler", "Loose Leaf Tea Sampler (12 Blends)", "coffee-tea", 29.0, 2, 60, "loose leaf tea tins",
       "Twelve tins of loose-leaf tea from chai to chamomile, with a steel infuser.",
       ["tea", "reading"], ["mothers_day", "thank_you", "get_well", "christmas"], ["mom", "grandparent", "teacher", "coworker", "anyone"])),
    G(("insulated-travel-mug", "Insulated Travel Mug", "coffee-tea", 24.0, 2, 80, "travel coffee mug",
       "Leak-proof double-wall mug that keeps drinks hot for 8 hours.",
       ["coffee", "travel", "commuting"], ["birthday", "graduation", "just_because", "corporate"], ["coworker", "teen", "friend", "anyone"])),
    G(("personalized-name-mug", "Personalized Name Mug", "coffee-tea", 19.0, 5, 100, "white ceramic mug",
       "Stoneware mug printed with a name or short message of your choice.",
       ["coffee", "tea", "personalized"], ["birthday", "mothers_day", "fathers_day", "thank_you"], ["mom", "dad", "teacher", "grandparent", "anyone"])),
    G(("coffee-lovers-hamper", "Coffee Lover's Hamper", "hampers", 79.0, 3, 15, "coffee gift basket",
       "Beans, biscotti, dark chocolate, a French press and a cozy mug in a keepsake crate.",
       ["coffee", "chocolate"], ["birthday", "christmas", "corporate", "thank_you"], ["dad", "boss", "coworker", "friend"])),

    # --- Plants & gardening ---------------------------------------------------
    G(("monstera-plant", "Monstera Deliciosa in Ceramic Pot", "plants", 55.0, 4, 12, "monstera plant pot",
       "A lush 60cm Monstera in a matte ceramic pot, easy-care and air-purifying.",
       ["plants", "home decor", "gardening"], ["housewarming", "birthday", "just_because"], ["friend", "partner", "mom", "her", "anyone"])),
    G(("succulent-trio", "Succulent Trio in Concrete Planters", "plants", 32.0, 3, 35, "succulents concrete pots",
       "Three low-maintenance succulents in hand-poured concrete planters.",
       ["plants", "home decor"], ["housewarming", "thank_you", "corporate", "just_because"], ["coworker", "teacher", "friend", "anyone"])),
    G(("gardening-tool-set", "Premium Gardening Tool Set", "gardening", 64.0, 3, 20, "gardening tools canvas bag",
       "Ash-handled trowel, fork, pruners and gloves in a waxed canvas tote.",
       ["gardening", "outdoors"], ["mothers_day", "birthday", "retirement", "fathers_day"], ["mom", "dad", "grandparent", "anyone"])),
    G(("herb-garden-kit", "Indoor Herb Garden Kit", "gardening", 38.0, 2, 45, "herb garden kitchen windowsill",
       "Grow basil, mint, parsley and chives on a windowsill; pots, soil and seeds included.",
       ["gardening", "cooking", "plants"], ["housewarming", "mothers_day", "just_because", "birthday"], ["mom", "friend", "partner", "anyone"])),
    G(("bonsai-starter", "Juniper Bonsai Starter Tree", "plants", 68.0, 5, 8, "bonsai tree",
       "A 5-year juniper bonsai with care guide, shears and humidity tray.",
       ["plants", "gardening", "mindfulness", "japanese culture"], ["retirement", "birthday", "fathers_day", "congratulations"], ["dad", "grandparent", "boss", "him"])),
    G(("orchid-in-pot", "White Phalaenopsis Orchid", "plants", 45.0, 2, 22, "white orchid",
       "Elegant double-stem orchid that blooms for months, in a glazed pot.",
       ["plants", "home decor"], ["mothers_day", "get_well", "thank_you", "anniversary"], ["mom", "her", "grandparent", "host", "wife"])),
    G(("personalized-garden-apron", "Personalized Garden Apron", "gardening", 36.0, 6, 30, "gardening apron",
       "Heavy canvas apron with pockets, embroidered with a name.",
       ["gardening", "personalized"], ["mothers_day", "birthday", "retirement"], ["mom", "grandparent", "anyone"])),
    G(("seed-bank-collection", "Heirloom Seed Collection (20 Varieties)", "gardening", 27.0, 2, 50, "seed packets",
       "Twenty packets of heirloom vegetable and flower seeds in a wooden box.",
       ["gardening", "sustainability"], ["birthday", "just_because", "christmas"], ["dad", "mom", "friend", "anyone"])),

    # --- Chocolates, sweets & food --------------------------------------------
    G(("artisan-chocolate-box", "Artisan Chocolate Box (24 pcs)", "chocolates", 39.0, 2, 70, "luxury chocolate box",
       "Twenty-four handmade truffles and pralines in a gold-foiled gift box.",
       ["chocolate", "sweets"], ["valentines", "anniversary", "thank_you", "birthday", "eid", "christmas"], ["wife", "partner", "her", "host", "anyone"])),
    G(("dates-and-nuts-platter", "Premium Dates & Nuts Platter", "chocolates", 46.0, 3, 30, "dates nuts platter",
       "Medjool dates, pistachios, almonds and cashews on a reusable brass tray.",
       ["food", "sweets"], ["eid", "housewarming", "corporate", "thank_you"], ["host", "grandparent", "boss", "anyone"])),
    G(("french-macaron-box", "French Macaron Box (18 pcs)", "chocolates", 32.0, 1, 25, "macarons box",
       "Eighteen pastel macarons in six flavours, baked fresh and shipped next day.",
       ["sweets", "baking"], ["birthday", "thank_you", "mothers_day", "valentines"], ["her", "mom", "friend", "coworker"])),
    G(("hot-sauce-sampler", "Small-Batch Hot Sauce Sampler", "food", 30.0, 3, 40, "hot sauce bottles",
       "Six small-batch hot sauces from mild smoky chipotle to ghost pepper.",
       ["cooking", "spicy food", "bbq"], ["birthday", "fathers_day", "christmas", "just_because"], ["dad", "him", "friend", "sibling"])),
    G(("gourmet-snack-hamper", "Gourmet Snack Hamper", "hampers", 89.0, 3, 14, "gourmet gift basket",
       "Crackers, cheeses, olives, jams and chocolate in a wicker basket.",
       ["food", "entertaining"], ["corporate", "thank_you", "christmas", "housewarming", "congratulations"], ["boss", "coworker", "host", "anyone"])),
    G(("honey-tasting-set", "Raw Honey Tasting Set", "food", 28.0, 3, 35, "honey jars",
       "Four raw honeys (wildflower, acacia, sidr, buckwheat) with a wooden dipper.",
       ["food", "wellness", "tea"], ["mothers_day", "get_well", "eid", "thank_you"], ["mom", "grandparent", "teacher", "anyone"])),
    G(("baking-kit-cookies", "Cookie Baking Kit", "food", 26.0, 3, 28, "cookie baking ingredients",
       "Pre-measured dry ingredients, cutters and recipe cards for three kinds of cookies.",
       ["baking", "cooking", "family time"], ["birthday", "christmas", "just_because"], ["kid", "teen", "mom", "friend"])),

    # --- Candles, spa & wellness ----------------------------------------------
    G(("soy-candle-trio", "Hand-Poured Soy Candle Trio", "home-fragrance", 34.0, 3, 55, "soy candles",
       "Three 200g soy candles: cedar & vanilla, fig, and sea salt.",
       ["home decor", "relaxation", "self care"], ["birthday", "housewarming", "thank_you", "just_because"], ["her", "friend", "host", "teacher", "anyone"])),
    G(("aromatherapy-diffuser", "Ultrasonic Aroma Diffuser + Oils", "home-fragrance", 49.0, 2, 30, "essential oil diffuser",
       "Wood-grain diffuser with ambient light and six pure essential oils.",
       ["wellness", "relaxation", "self care"], ["mothers_day", "get_well", "birthday"], ["mom", "wife", "her", "friend"])),
    G(("spa-gift-box", "At-Home Spa Gift Box", "wellness", 58.0, 3, 26, "spa gift set bath",
       "Bath salts, body scrub, sheet masks, a candle and a waffle robe.",
       ["self care", "relaxation", "beauty"], ["mothers_day", "birthday", "valentines", "get_well"], ["mom", "wife", "her", "sibling", "friend"])),
    G(("weighted-blanket", "Weighted Blanket (7 kg)", "wellness", 89.0, 4, 10, "weighted blanket bed",
       "Breathable cotton weighted blanket for calmer, deeper sleep.",
       ["sleep", "wellness", "self care"], ["birthday", "get_well", "just_because"], ["partner", "friend", "teen", "anyone"])),
    G(("yoga-starter-bundle", "Yoga Starter Bundle", "fitness", 62.0, 3, 20, "yoga mat blocks",
       "Cork yoga mat, two blocks, strap and a 30-day beginner program card.",
       ["yoga", "fitness", "wellness"], ["birthday", "just_because", "graduation"], ["her", "friend", "partner", "sibling"])),
    G(("silk-sleep-set", "Mulberry Silk Sleep Set", "wellness", 54.0, 3, 24, "silk eye mask pillowcase",
       "Silk pillowcase and eye mask in a keepsake box, gentle on hair and skin.",
       ["sleep", "beauty", "self care"], ["anniversary", "valentines", "mothers_day", "birthday"], ["wife", "her", "mom", "partner"])),
    G(("massage-gun", "Mini Percussion Massage Gun", "fitness", 79.0, 2, 15, "massage gun",
       "Pocket-size massage gun with four heads and 6-hour battery.",
       ["fitness", "running", "wellness"], ["birthday", "fathers_day", "christmas"], ["him", "husband", "dad", "friend", "coworker"])),

    # --- Books, stationery & creativity ---------------------------------------
    G(("leather-journal", "Personalized Leather Journal", "stationery", 44.0, 6, 32, "leather journal",
       "Refillable full-grain leather journal embossed with initials.",
       ["writing", "journaling", "personalized", "travel"], ["graduation", "birthday", "retirement", "anniversary"], ["teen", "him", "her", "boss", "anyone"])),
    G(("fountain-pen-set", "Fountain Pen Gift Set", "stationery", 58.0, 3, 20, "fountain pen ink",
       "Brass fountain pen with converter, two ink bottles and a walnut case.",
       ["writing", "calligraphy"], ["graduation", "retirement", "corporate", "fathers_day"], ["boss", "dad", "teacher", "him"])),
    G(("watercolor-kit", "Watercolor Painting Kit", "art-supplies", 46.0, 3, 25, "watercolor paint set",
       "24 artist-grade pans, three brushes, cold-press pad and a beginner guide.",
       ["painting", "art", "creativity"], ["birthday", "just_because", "retirement"], ["teen", "kid", "mom", "grandparent", "friend"])),
    G(("calligraphy-starter", "Modern Calligraphy Starter Kit", "art-supplies", 29.0, 3, 30, "calligraphy pen practice",
       "Oblique holder, nibs, ink and practice sheets for modern lettering.",
       ["calligraphy", "art", "writing"], ["birthday", "just_because"], ["her", "teen", "friend", "sibling"])),
    G(("book-lovers-box", "Book Lover's Box", "books", 52.0, 3, 18, "books tea blanket reading",
       "A staff-picked novel, bookmark, reading light and a tea blend in a gift box.",
       ["reading", "tea"], ["birthday", "get_well", "christmas", "just_because"], ["mom", "friend", "teacher", "grandparent", "anyone"])),
    G(("cookbook-world-kitchens", "World Kitchens Cookbook", "books", 35.0, 2, 40, "cookbook kitchen",
       "Hardcover cookbook with 150 home-style recipes from 30 countries.",
       ["cooking", "travel", "reading"], ["housewarming", "birthday", "wedding", "christmas"], ["host", "partner", "friend", "mom", "anyone"])),
    G(("kindle-leather-cover", "E-Reader with Leather Cover", "books", 139.0, 2, 10, "ereader kindle reading",
       "Glare-free 6.8\" e-reader with warm light, bundled with a handmade leather cover.",
       ["reading", "travel", "tech"], ["birthday", "graduation", "retirement", "christmas"], ["mom", "dad", "teen", "grandparent", "anyone"])),
    G(("gratitude-journal", "Five-Minute Gratitude Journal", "stationery", 22.0, 2, 60, "gratitude journal notebook",
       "Guided daily journal with prompts for gratitude and reflection.",
       ["journaling", "mindfulness", "self care"], ["just_because", "get_well", "graduation", "birthday"], ["friend", "teen", "sibling", "her", "anyone"])),

    # --- Kitchen & entertaining ------------------------------------------------
    G(("cheese-board-set", "Acacia Cheese Board & Knife Set", "kitchen", 49.0, 3, 25, "cheese board knives",
       "Large acacia board with slide-out drawer of four cheese knives.",
       ["entertaining", "cooking", "wine"], ["housewarming", "wedding", "christmas", "thank_you"], ["host", "partner", "friend", "anyone"])),
    G(("cast-iron-skillet", "Pre-Seasoned Cast Iron Skillet", "kitchen", 45.0, 3, 30, "cast iron skillet",
       "30cm skillet that will outlive us all, with silicone handle cover.",
       ["cooking", "bbq"], ["housewarming", "wedding", "fathers_day", "birthday"], ["dad", "husband", "him", "friend"])),
    G(("spice-rack-kit", "Global Spice Collection (16 Jars)", "kitchen", 54.0, 3, 20, "spice jars rack",
       "Sixteen magnetic jars of whole and ground spices with recipe booklet.",
       ["cooking", "travel"], ["housewarming", "wedding", "birthday"], ["mom", "partner", "host", "anyone"])),
    G(("pasta-making-kit", "Pasta Making Kit", "kitchen", 58.0, 4, 16, "fresh pasta making",
       "Beech-wood rolling pin, cutter wheel, drying rack and semolina for fresh pasta.",
       ["cooking", "italian food", "family time"], ["anniversary", "wedding", "birthday", "housewarming"], ["partner", "wife", "husband", "friend"])),
    G(("whiskey-stones-set", "Whiskey Stones & Glass Set", "barware", 39.0, 2, 35, "whiskey glass stones",
       "Two crystal tumblers, nine soapstone chilling stones and a walnut tray.",
       ["entertaining", "home bar"], ["fathers_day", "birthday", "anniversary", "retirement"], ["dad", "husband", "boss", "him"])),
    G(("mocktail-kit", "Craft Mocktail Kit", "barware", 44.0, 3, 22, "mocktail glass cocktail shaker",
       "Shaker, jigger, muddler and four botanical syrups for alcohol-free drinks.",
       ["entertaining", "home bar", "wellness"], ["housewarming", "birthday", "eid", "christmas"], ["host", "friend", "partner", "anyone"])),
    G(("bbq-tool-set", "BBQ Grill Master Tool Set", "outdoor", 59.0, 3, 20, "bbq grill tools",
       "Stainless spatula, tongs, fork, brush and meat thermometer in a roll-up case.",
       ["bbq", "cooking", "outdoors"], ["fathers_day", "birthday", "housewarming"], ["dad", "husband", "him", "friend"])),

    # --- Tech & gadgets --------------------------------------------------------
    G(("wireless-charging-stand", "3-in-1 Wireless Charging Stand", "tech", 49.0, 2, 40, "wireless charger stand phone",
       "Charges phone, earbuds and watch at once; foldable for travel.",
       ["tech", "travel", "gadgets"], ["birthday", "graduation", "christmas", "corporate"], ["him", "teen", "coworker", "boss", "anyone"])),
    G(("bluetooth-speaker", "Waterproof Bluetooth Speaker", "tech", 59.0, 2, 30, "bluetooth speaker outdoor",
       "Rugged 20-hour speaker with deep bass, waterproof to 1m.",
       ["music", "outdoors", "tech"], ["birthday", "graduation", "just_because"], ["teen", "friend", "him", "sibling"])),
    G(("instant-camera", "Instant Film Camera Bundle", "tech", 99.0, 2, 14, "instant camera polaroid",
       "Instant camera with 20 film shots, strap and a photo album.",
       ["photography", "travel", "memories"], ["birthday", "graduation", "wedding", "valentines"], ["teen", "her", "friend", "partner"])),
    G(("smart-mug", "Temperature-Control Smart Mug", "tech", 129.0, 2, 12, "smart mug desk",
       "App-controlled mug that keeps coffee at your chosen temperature for 90 minutes.",
       ["coffee", "tech", "gadgets"], ["birthday", "christmas", "corporate", "retirement"], ["boss", "dad", "coworker", "anyone"])),
    G(("digital-photo-frame", "Wi-Fi Digital Photo Frame", "tech", 119.0, 3, 16, "digital photo frame",
       "10\" frame the family can send photos to from their phones.",
       ["family time", "memories", "photography"], ["mothers_day", "fathers_day", "christmas", "birthday"], ["grandparent", "mom", "dad"])),
    G(("noise-cancelling-earbuds", "Noise-Cancelling Earbuds", "tech", 89.0, 2, 25, "wireless earbuds case",
       "Active noise cancellation, 30-hour case battery, sweat resistant.",
       ["music", "tech", "commuting", "fitness"], ["birthday", "graduation", "christmas"], ["teen", "him", "her", "sibling", "friend"])),
    G(("star-projector", "Galaxy Star Projector Night Light", "tech", 36.0, 2, 38, "galaxy projector bedroom",
       "Projects a slowly moving nebula and stars; remote and timer included.",
       ["space", "relaxation", "sleep"], ["birthday", "christmas", "just_because"], ["kid", "teen", "sibling"])),
    G(("smart-tracker-4pack", "Bluetooth Item Trackers (4-pack)", "tech", 69.0, 2, 30, "keys wallet tracker",
       "Find keys, wallet and bags from your phone; one-year battery.",
       ["travel", "tech", "gadgets"], ["birthday", "fathers_day", "christmas"], ["dad", "grandparent", "him", "anyone"])),

    # --- Jewellery & accessories (personalized) --------------------------------
    G(("initial-necklace", "Gold-Plated Initial Necklace", "jewellery", 49.0, 5, 40, "gold initial necklace",
       "Dainty 18k gold-plated pendant engraved with an initial.",
       ["jewellery", "personalized", "fashion"], ["birthday", "valentines", "mothers_day", "anniversary"], ["her", "wife", "mom", "sibling", "friend"])),
    G(("birthstone-bracelet", "Birthstone Charm Bracelet", "jewellery", 58.0, 5, 30, "charm bracelet birthstone",
       "Sterling silver bracelet with a genuine birthstone charm.",
       ["jewellery", "personalized"], ["birthday", "mothers_day", "graduation"], ["her", "mom", "teen", "grandparent"])),
    G(("engraved-cufflinks", "Engraved Silver Cufflinks", "jewellery", 65.0, 6, 20, "silver cufflinks",
       "Brushed sterling cufflinks engraved with initials, in a leather box.",
       ["fashion", "personalized"], ["wedding", "anniversary", "fathers_day", "graduation"], ["husband", "dad", "him", "boss"])),
    G(("leather-wallet-personalized", "Personalized Leather Wallet", "accessories", 55.0, 5, 35, "leather wallet",
       "Slim full-grain bifold with RFID blocking and an embossed monogram.",
       ["fashion", "personalized"], ["fathers_day", "birthday", "anniversary", "graduation"], ["dad", "husband", "him", "teen"])),
    G(("cashmere-scarf", "Cashmere Blend Scarf", "accessories", 72.0, 3, 25, "cashmere scarf",
       "Soft cashmere-wool scarf in heather grey, gift-boxed.",
       ["fashion", "winter"], ["christmas", "birthday", "mothers_day", "anniversary"], ["mom", "her", "grandparent", "him", "anyone"])),
    G(("couple-keychains", "Matching Couple Keychains", "accessories", 26.0, 5, 50, "heart keychain couple",
       "Two interlocking brass keychains engraved with names and a date.",
       ["personalized", "romance"], ["valentines", "anniversary"], ["partner", "wife", "husband"])),

    # --- Home decor & keepsakes -------------------------------------------------
    G(("custom-star-map", "Custom Star Map Print", "home-decor", 59.0, 6, 99, "star map print frame",
       "Framed print of the night sky from a date and place that matters.",
       ["personalized", "romance", "memories", "space"], ["anniversary", "valentines", "wedding", "birthday"], ["partner", "wife", "husband", "friend"])),
    G(("family-photo-book", "Custom Family Photo Book", "home-decor", 49.0, 7, 99, "photo album book",
       "40-page linen hardcover photo book designed from your uploads.",
       ["memories", "family time", "personalized"], ["mothers_day", "fathers_day", "anniversary", "retirement"], ["mom", "dad", "grandparent", "partner"])),
    G(("macrame-wall-hanging", "Handwoven Macrame Wall Hanging", "home-decor", 39.0, 4, 18, "macrame wall hanging",
       "Boho cotton macrame on a driftwood rod, 60cm wide.",
       ["home decor", "handmade"], ["housewarming", "birthday", "just_because"], ["her", "friend", "host", "sibling"])),
    G(("brass-table-lamp", "Mushroom Brass Table Lamp", "home-decor", 85.0, 4, 12, "brass table lamp",
       "Rechargeable cordless lamp with dimmable warm light.",
       ["home decor", "reading"], ["housewarming", "wedding", "birthday"], ["partner", "host", "friend", "anyone"])),
    G(("knit-throw-blanket", "Chunky Knit Throw Blanket", "home-decor", 64.0, 3, 20, "chunky knit blanket",
       "Hand-knit chenille throw, machine washable, 120x150cm.",
       ["home decor", "relaxation", "winter"], ["housewarming", "christmas", "mothers_day", "get_well"], ["mom", "grandparent", "friend", "partner", "anyone"])),
    G(("wedding-vows-print", "Wedding Vows Keepsake Print", "home-decor", 69.0, 7, 99, "wedding frame print",
       "Typeset print of the couple's vows or first-dance song in an oak frame.",
       ["romance", "personalized", "memories"], ["wedding", "anniversary"], ["partner", "wife", "husband", "friend"])),
    G(("arabic-calligraphy-art", "Arabic Calligraphy Wall Art", "home-decor", 75.0, 5, 15, "arabic calligraphy art",
       "Gold-leaf calligraphy on black canvas, 40x60cm, ready to hang.",
       ["home decor", "calligraphy", "art"], ["eid", "housewarming", "wedding"], ["host", "partner", "grandparent", "anyone"])),
    G(("brass-lantern-set", "Moroccan Brass Lantern Set", "home-decor", 58.0, 4, 16, "moroccan lantern",
       "Two pierced-brass lanterns that throw patterned light, with LED candles.",
       ["home decor", "entertaining"], ["eid", "diwali", "housewarming", "wedding"], ["host", "mom", "friend", "anyone"])),
    G(("diya-gift-set", "Hand-Painted Diya Gift Set", "home-decor", 24.0, 4, 40, "diya lamps",
       "Twelve hand-painted clay diyas with scented wax, in a festive box.",
       ["home decor", "festivals"], ["diwali", "housewarming", "thank_you"], ["host", "mom", "friend", "anyone"])),

    # --- Kids, toys & games ------------------------------------------------------
    G(("stem-robot-kit", "Build-Your-Own Robot STEM Kit", "toys", 49.0, 2, 30, "robot kit children",
       "Twelve robot builds with motors and sensors; ages 8+.",
       ["science", "robotics", "building"], ["birthday", "christmas", "graduation"], ["kid", "teen"])),
    G(("wooden-train-set", "Wooden Train Set (50 pcs)", "toys", 55.0, 3, 20, "wooden train set toy",
       "Beech-wood tracks, bridge and magnetic trains; ages 3+.",
       ["building", "imaginative play"], ["birthday", "christmas", "eid"], ["kid"])),
    G(("art-easel-kids", "Kids' Double-Sided Art Easel", "toys", 69.0, 4, 10, "kids art easel",
       "Chalkboard/whiteboard easel with paper roll, paints and storage tray.",
       ["art", "painting", "creativity"], ["birthday", "christmas"], ["kid"])),
    G(("board-game-night", "Family Board Game Night Bundle", "games", 59.0, 2, 25, "board games family",
       "Three award-winning board games for ages 8 to 80.",
       ["games", "family time", "entertaining"], ["christmas", "housewarming", "birthday", "eid"], ["kid", "teen", "host", "anyone"])),
    G(("jigsaw-1000", "Illustrated 1000-Piece Jigsaw Puzzle", "games", 25.0, 2, 45, "jigsaw puzzle",
       "Richly illustrated world-map puzzle in a keepsake tin.",
       ["puzzles", "relaxation", "travel"], ["birthday", "get_well", "retirement", "christmas"], ["grandparent", "mom", "friend", "anyone"])),
    G(("plush-bunny", "Organic Cotton Plush Bunny", "baby", 29.0, 2, 40, "plush bunny toy",
       "Super-soft organic plush, safe from birth, with name tag.",
       ["cuddly toys"], ["new_baby", "birthday", "eid"], ["baby", "kid"])),
    G(("baby-milestone-set", "Baby Milestone Blanket & Cards", "baby", 42.0, 3, 25, "baby milestone blanket",
       "Muslin blanket with month markers and 30 milestone photo cards.",
       ["memories", "photography"], ["new_baby"], ["baby"])),
    G(("new-parent-hamper", "New Parents Survival Hamper", "hampers", 95.0, 3, 12, "baby gift basket",
       "Swaddles, baby lotion, snacks and coffee for exhausted new parents.",
       ["family time", "self care"], ["new_baby"], ["baby", "friend", "sibling", "coworker"])),
    G(("telescope-kids", "Beginner Telescope", "toys", 89.0, 3, 10, "telescope stars kid",
       "70mm refractor with tripod, phone adapter and star guide.",
       ["space", "science", "outdoors"], ["birthday", "christmas", "graduation"], ["kid", "teen"])),
    G(("lego-style-flowers", "Botanical Building Brick Bouquet", "toys", 59.0, 2, 20, "brick flower bouquet",
       "Build-it-yourself bouquet of roses and wildflowers that never wilts.",
       ["building", "home decor", "plants"], ["valentines", "mothers_day", "anniversary", "birthday"], ["her", "teen", "partner", "friend"])),

    # --- Outdoors, travel & fitness ----------------------------------------------
    G(("hiking-daypack", "Lightweight Hiking Daypack", "outdoor", 65.0, 2, 22, "hiking backpack mountain",
       "20L packable daypack with hydration sleeve and rain cover.",
       ["hiking", "outdoors", "travel"], ["birthday", "graduation", "just_because"], ["him", "her", "teen", "friend"])),
    G(("travel-organizer-set", "Travel Organizer Set", "travel", 38.0, 2, 40, "packing cubes travel",
       "Six compression packing cubes, toiletry bag and passport wallet.",
       ["travel"], ["graduation", "birthday", "wedding", "retirement"], ["friend", "teen", "partner", "anyone"])),
    G(("scratch-world-map", "Scratch-Off World Travel Map", "travel", 32.0, 3, 35, "scratch world map",
       "Scratch off every country you visit; framed poster with accessories.",
       ["travel", "memories"], ["graduation", "anniversary", "retirement", "birthday"], ["partner", "friend", "teen", "anyone"])),
    G(("camping-hammock", "Parachute Camping Hammock", "outdoor", 42.0, 2, 30, "hammock camping forest",
       "Two-person nylon hammock with tree straps, packs to the size of a mango.",
       ["camping", "outdoors", "relaxation"], ["birthday", "just_because", "fathers_day"], ["him", "friend", "teen", "husband"])),
    G(("smart-water-bottle", "Insulated Smart Water Bottle", "fitness", 45.0, 2, 30, "water bottle gym",
       "LED-cap bottle that reminds you to hydrate and keeps drinks cold 24h.",
       ["fitness", "wellness", "running"], ["birthday", "just_because", "corporate"], ["coworker", "friend", "her", "him"])),
    G(("golf-accessory-kit", "Golfer's Accessory Kit", "sports", 48.0, 3, 18, "golf balls tees",
       "Personalized golf balls, divot tool, tees and towel in a leather pouch.",
       ["golf", "sports", "personalized"], ["fathers_day", "retirement", "birthday", "corporate"], ["dad", "boss", "grandparent", "him"])),
    G(("cricket-bat-signed-style", "English Willow Cricket Bat", "sports", 99.0, 4, 8, "cricket bat",
       "Grade-2 English willow bat with grip and cover.",
       ["cricket", "sports"], ["birthday", "eid", "graduation"], ["teen", "him", "sibling", "kid"])),

    # --- Pets ----------------------------------------------------------------------
    G(("dog-birthday-box", "Dog Birthday Box", "pets", 39.0, 3, 25, "dog toys treats",
       "Squeaky toys, a bandana and all-natural treats for a very good dog.",
       ["dogs", "pets"], ["birthday", "just_because", "christmas"], ["friend", "sibling", "anyone"])),
    G(("custom-pet-portrait", "Custom Pet Portrait", "pets", 79.0, 7, 99, "dog portrait painting",
       "Digital illustration of their pet from a photo, printed on canvas.",
       ["pets", "art", "personalized", "dogs", "cats"], ["birthday", "christmas", "just_because", "get_well"], ["friend", "mom", "partner", "anyone"])),
    G(("cat-tree-lounger", "Modern Cat Tree Lounger", "pets", 89.0, 5, 10, "cat tree modern",
       "Sisal scratcher and felt bed in a sleek plywood tower.",
       ["cats", "pets"], ["birthday", "housewarming", "christmas"], ["friend", "sibling", "anyone"])),

    # --- Music & hobbies -------------------------------------------------------------
    G(("vinyl-record-player", "Suitcase Vinyl Record Player", "music", 79.0, 3, 14, "record player vinyl",
       "Retro turntable with built-in speakers and Bluetooth in.",
       ["music", "vintage"], ["birthday", "anniversary", "christmas", "graduation"], ["partner", "teen", "dad", "friend"])),
    G(("ukulele-starter", "Concert Ukulele Starter Pack", "music", 59.0, 3, 15, "ukulele",
       "Mahogany ukulele with gig bag, tuner, strap and chord book.",
       ["music", "learning"], ["birthday", "graduation", "christmas"], ["teen", "kid", "friend", "sibling"])),
    G(("pottery-class-kit", "Air-Dry Clay Pottery Kit", "art-supplies", 34.0, 3, 25, "pottery clay hands",
       "Air-dry clay, tools, paints and video lessons for six projects.",
       ["pottery", "art", "creativity", "handmade"], ["birthday", "just_because", "retirement"], ["her", "friend", "mom", "teen"])),
    G(("chess-set-wooden", "Handcrafted Wooden Chess Set", "games", 69.0, 3, 16, "wooden chess board",
       "Folding sheesham-wood board with weighted, hand-carved pieces.",
       ["chess", "games", "strategy"], ["birthday", "graduation", "retirement", "fathers_day"], ["dad", "grandparent", "teen", "him"])),
    G(("knitting-kit", "Learn-to-Knit Beanie Kit", "art-supplies", 36.0, 3, 20, "knitting yarn needles",
       "Merino yarn, bamboo needles and a step-by-step pattern for a beanie.",
       ["knitting", "handmade", "creativity"], ["birthday", "christmas", "retirement", "get_well"], ["grandparent", "mom", "her", "friend"])),

    # --- Corporate & thank-you ---------------------------------------------------------
    G(("desk-organizer-walnut", "Walnut Desk Organizer", "office", 54.0, 3, 20, "wooden desk organizer",
       "Solid walnut organizer with phone stand, pen slots and tray.",
       ["productivity", "home office"], ["corporate", "graduation", "retirement", "thank_you"], ["boss", "coworker", "teacher", "anyone"])),
    G(("teacher-thank-you-box", "Teacher Appreciation Box", "hampers", 35.0, 2, 30, "thank you gift box apple",
       "Engraved pen, tea sampler, hand cream and a thank-you card.",
       ["tea", "writing"], ["thank_you", "graduation"], ["teacher"])),
    G(("farewell-hamper", "Farewell & Retirement Hamper", "hampers", 99.0, 3, 10, "gift hamper champagne flowers",
       "Sparkling juice, gourmet treats, a memory book and a scented candle.",
       ["entertaining", "memories"], ["retirement", "corporate", "congratulations"], ["boss", "coworker", "grandparent"])),

    # --- Flowers & experiences -----------------------------------------------------------
    G(("preserved-rose-dome", "Preserved Rose in Glass Dome", "flowers", 59.0, 3, 20, "rose glass dome",
       "A real rose preserved to last years, under a glass cloche.",
       ["romance", "home decor", "flowers"], ["valentines", "anniversary", "mothers_day"], ["wife", "partner", "her", "mom"])),
    G(("dried-flower-bouquet", "Dried Flower Bouquet", "flowers", 44.0, 3, 25, "dried flowers bouquet",
       "Pampas, lavender and bunny tails that stay beautiful for a year.",
       ["flowers", "home decor"], ["birthday", "housewarming", "thank_you", "get_well"], ["her", "mom", "friend", "host"])),
    G(("fresh-seasonal-bouquet", "Fresh Seasonal Bouquet", "flowers", 49.0, 1, 30, "fresh flower bouquet",
       "Florist's choice of seasonal blooms, delivered next day.",
       ["flowers"], ["birthday", "anniversary", "get_well", "thank_you", "mothers_day", "valentines"], ["her", "mom", "wife", "anyone"])),
    G(("cooking-class-voucher", "Online Cooking Class for Two", "experiences", 70.0, 0, 999, "cooking class couple",
       "Live two-hour online class with a chef; ingredient list sent in advance.",
       ["cooking", "romance", "learning"], ["anniversary", "valentines", "wedding", "birthday"], ["partner", "wife", "husband", "friend"])),
    G(("digital-gift-card", "GiftVoice e-Gift Card", "experiences", 50.0, 0, 9999, "gift card envelope",
       "Delivered instantly by email with your message; any amount up to $500.",
       ["anything"], ["birthday", "thank_you", "christmas", "eid", "corporate", "just_because"], ["anyone"])),

    # --- Out of stock (exercises stock filtering) ----------------------------------------------
    G(("limited-advent-calendar", "Luxury Tea Advent Calendar", "coffee-tea", 65.0, 3, 0, "advent calendar",
       "24 days of luxury teas in a keepsake drawer box. Sold out until next season.",
       ["tea"], ["christmas"], ["mom", "friend", "anyone"])),
]
